#!/bin/sh

if [ -f "Makefile" ]; then
	make distclean
fi

chmod 644 * -R
chmod +x autogen.sh $0

if [ -f "configure" ]; then
	rm -rf  configure
fi

sh autogen.sh

if [ ! -f "configure" ]; then
	echo ""
	echo " --------- Run autogen Error! --------- "
	echo ""
	exit 2
fi

rm config.cache config.status -f
PATH="/work/toolchain_R3/usr/bin:/work/toolchain_R3/usr/sbin/:$PATH" \
AR="/work/toolchain_R3/usr/bin/arm-none-linux-gnueabi-ar" \
AS="/work/toolchain_R3/usr/bin/arm-none-linux-gnueabi-as" \
LD="/work/toolchain_R3/usr/bin/arm-none-linux-gnueabi-ld" \
NM="/work/toolchain_R3/usr/bin/arm-none-linux-gnueabi-nm" \
CC="/work/toolchain_R3/usr/bin/arm-none-linux-gnueabi-gcc" \
GCC="/work/toolchain_R3/usr/bin/arm-none-linux-gnueabi-gcc" \
CPP="/work/toolchain_R3/usr/bin/arm-none-linux-gnueabi-cpp" \
CXX="/work/toolchain_R3/usr/bin/arm-none-linux-gnueabi-g++" \
FC="/work/toolchain_R3/usr/bin/arm-none-linux-gnueabi-gfortran" \
RANLIB="/work/toolchain_R3/usr/bin/arm-none-linux-gnueabi-ranlib" \
STRIP="/work/toolchain_R3/usr/bin/arm-none-linux-gnueabi-strip" \
OBJCOPY="/work/toolchain_R3/usr/bin/arm-none-linux-gnueabi-objcopy" \
OBJDUMP="/work/toolchain_R3/usr/bin/arm-none-linux-gnueabi-objdump" \
./configure --target=arm-none-linux-gnueabi \
	--host=arm-none-linux-gnueabi \
	--build=i686-pc-linux-gnu \
	--prefix=/work/toolchain_R3/usr/arm-R3-linux-gnueabi/sysroot/usr

if [ -f "Makefile" ]; then
	make clean
fi